# payment - dev overrides. Only values that differ from values.yaml.
environment: dev
namespace: roboshop-dev

replicaCount: 1
image:
  tag: "2.0.1"

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: "250m"
    memory: 256Mi

podDisruptionBudget:
  enabled: false
  minAvailable: 1

topologySpreadConstraints:
  enabled: false
  maxSkew: 1
  topologyKey: topology.kubernetes.io/zone
  whenUnsatisfiable: ScheduleAnyway

nodeSelector: {}

commonAnnotations:
  argocd.argoproj.io/sync-wave: "1"
  roboshop.io/environment: "dev"
