{{- if .Values.resourceQuota.enabled }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: roboshop-quota
  namespace: {{ include "platform.namespace" . }}
  labels:
    {{- include "platform.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-9"
spec:
  hard:
    {{- toYaml .Values.resourceQuota.hard | nindent 4 }}
{{- end }}
