# mysql - qa overrides. Only values that differ from values.yaml.
environment: qa
namespace: roboshop-qa

image:
  tag: "2.0.0"

persistence:
  storageClass: gp3
  size: 10Gi

nodeSelector: {}

commonAnnotations:
  argocd.argoproj.io/sync-wave: "0"
  roboshop.io/environment: "qa"
