spring.jmx.enabled=true

management.endpoint.info.enabled=true
management.endpoint.health.enabled=true
management.endpoint.metrics.enabled=true
management.endpoint.env.enabled=true

# Prometheus scraping for Kubernetes ServiceMonitor.
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true
