# --------------------------------------------------------------------------- #
# Roboshop application secret: roboshop/<environment>/app
#
# Provisions the AWS Secrets Manager secret consumed by the existing External
# Secret (charts/platform/templates/externalsecret.yaml). The eight key names
# below MUST exactly match the ExternalSecret data list in
# charts/platform/values.yaml.
#
# Flow:
#   Terraform -> AWS Secrets Manager roboshop/dev/app
#             -> ClusterSecretStore (aws-secretsmanager)
#             -> ExternalSecret (roboshop-secrets)
#             -> Kubernetes Secret roboshop-secrets
#
# Values are generated by the random provider at apply time and held only in
# the Terraform state. Nothing is committed to Git and nothing is exposed
# through Terraform outputs.
# --------------------------------------------------------------------------- #

locals {
  secret_name = "${var.project}/${var.environment}/app"

  # Character set for generated passwords. Excludes characters that are
  # awkward in shell scripts, SQL literals, or AMQP credentials:
  # double quote, backslash, single quote, dollar, backtick, whitespace.
  password_charset = "!@#%^&*()-_=+[]{}<>?"
}

data "aws_caller_identity" "current" {}

# --------------------------------------------------------------------------- #
# KMS: a dedicated customer-managed key so decryption is scoped to this secret
# only, instead of granting kms:Decrypt on the shared aws/secretsmanager key.
# Follows the existing convention of per-component KMS keys (see module eks).
# --------------------------------------------------------------------------- #
resource "aws_kms_key" "app" {
  description             = "Encrypts AWS Secrets Manager secret ${local.secret_name}"
  deletion_window_in_days = 7
  enable_key_rotation     = true
  policy = jsonencode({
    Version = "2012-10-17"
    Id      = "key-${var.project}-${var.environment}-app"
    Statement = [
      {
        Sid       = "EnableIAMRootPermissions"
        Effect    = "Allow"
        Principal = { AWS = "arn:aws:iam::${data.aws_caller_identity.current.account_id}:root" }
        Action    = "kms:*"
        Resource  = "*"
      },
      {
        Sid       = "AllowExternalSecretsDecrypt"
        Effect    = "Allow"
        Principal = { AWS = var.external_secrets_role_arn }
        Action    = ["kms:Decrypt", "kms:DescribeKey"]
        Resource  = "*"
      }
    ]
  })
  tags = var.tags
}

resource "aws_kms_alias" "app" {
  name          = "alias/${var.project}-${var.environment}-app-secrets"
  target_key_id = aws_kms_key.app.key_id
}

# --------------------------------------------------------------------------- #
# Random values. Generated at apply time and stored only in state. Every
# resource is sensitive; none of the .result values are exposed by outputs.
# --------------------------------------------------------------------------- #
resource "random_password" "jwt_access" {
  length           = 64
  special          = true
  override_special = local.password_charset
  min_lower        = 1
  min_upper        = 1
  min_numeric      = 1
  min_special      = 1
}

resource "random_password" "jwt_refresh" {
  length           = 64
  special          = true
  override_special = local.password_charset
  min_lower        = 1
  min_upper        = 1
  min_numeric      = 1
  min_special      = 1
}

resource "random_password" "mysql_root" {
  length           = 24
  special          = true
  override_special = local.password_charset
  min_lower        = 1
  min_upper        = 1
  min_numeric      = 1
  min_special      = 1
}

resource "random_password" "mysql_shipping" {
  length           = 24
  special          = true
  override_special = local.password_charset
  min_lower        = 1
  min_upper        = 1
  min_numeric      = 1
  min_special      = 1
}

resource "random_password" "amqp_pass" {
  length           = 24
  special          = true
  override_special = local.password_charset
  min_lower        = 1
  min_upper        = 1
  min_numeric      = 1
  min_special      = 1
}

resource "random_password" "rabbitmq_pass" {
  length           = 24
  special          = true
  override_special = local.password_charset
  min_lower        = 1
  min_upper        = 1
  min_numeric      = 1
  min_special      = 1
}

# Usernames are alphanumeric only (no special characters).
resource "random_string" "amqp_user" {
  length      = 16
  special     = false
  min_lower   = 1
  min_upper   = 1
  min_numeric = 1
}

resource "random_string" "rabbitmq_user" {
  length      = 16
  special     = false
  min_lower   = 1
  min_upper   = 1
  min_numeric = 1
}

# --------------------------------------------------------------------------- #
# The secret and its initial version. The JSON property names must match the
# ExternalSecret data keys 1:1 (charts/platform/values.yaml).
# --------------------------------------------------------------------------- #
resource "aws_secretsmanager_secret" "app" {
  name                    = local.secret_name
  description             = "Roboshop application secrets consumed by External Secrets (target Kubernetes Secret: roboshop-secrets)"
  kms_key_id              = aws_kms_key.app.arn
  recovery_window_in_days = var.recovery_window_in_days
  tags                    = var.tags
}

resource "aws_secretsmanager_secret_version" "app" {
  secret_id = aws_secretsmanager_secret.app.id

  secret_string = jsonencode({
    JWT_ACCESS_SECRET       = random_password.jwt_access.result
    JWT_REFRESH_SECRET      = random_password.jwt_refresh.result
    MYSQL_SHIPPING_PASSWORD = random_password.mysql_shipping.result
    MYSQL_ROOT_PASSWORD     = random_password.mysql_root.result
    AMQP_USER               = random_string.amqp_user.result
    AMQP_PASS               = random_password.amqp_pass.result
    RABBITMQ_DEFAULT_USER   = random_string.rabbitmq_user.result
    RABBITMQ_DEFAULT_PASS   = random_password.rabbitmq_pass.result
  })
}