# shipping - dev overrides. Only values that differ from values.yaml.
environment: dev
namespace: roboshop-dev
replicaCount: 1
image:
  tag: "3d955d055f6ed22fdce023149809560e3c2acd78"
  repository: roboshop/shipping
  digest: sha256:b464bf432a1fe6cec3170778d92f42621dd96a9dda097d08ec328bb22e4b1bed
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: "250m"
    memory: 256Mi
podDisruptionBudget:
  enabled: false
  minAvailable: 1
topologySpreadConstraints:
  enabled: false
  maxSkew: 1
  topologyKey: topology.kubernetes.io/zone
  whenUnsatisfiable: ScheduleAnyway
nodeSelector: {}
commonAnnotations:
  argocd.argoproj.io/sync-wave: "1"
  roboshop.io/environment: "dev"
